### PR TITLE
Re-add message to record dict

### PR DESCRIPTION
**Pull request by andela-sjames**
PR: https://themuse.atlassian.net/browse/PLAT-1491

### CODE REVIEW

**Comment by ian-axelrod** [comment]
Did you test this against the datadog agent?

**Comment by andela-sjames** [comment]
This is what I removed at first, the `message` key format is what allows Message on the dashboard to be properly formatted. I removed it when I removed the `extra` object from the previous commit.

**Comment by andela-sjames** [comment]
And yeah, this has been tested before now

**Comment by ian-axelrod** [comment]
Okay.

**Pull request merged**
